name: build
on:
  push:
    branches: [ Phase06 ]
  pull_request:
    branches: [ Phase06 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: "./Phase05/Search"
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: "./Phase05/Search"
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: "./Phase05/Search"